/**
 * ============================================================
 *  ADMIN-CONFIG.JS — YOUR CONTENT & SETTINGS
 *  Generated by Admin Panel — 2/25/2026, 6:59:38 PM
 *
 *  This is YOUR file. Claude never modifies this.
 *  Load order: admin-config.js FIRST, then admin.js
 * ============================================================
 */

var ADMIN_PIN = "3432";

var KB_DIRECTIONS = [
  {
    "label": "Zoom In",
    "value": "kb-zoom-in"
  },
  {
    "label": "Zoom Out",
    "value": "kb-zoom-out"
  },
  {
    "label": "Pan Left",
    "value": "kb-pan-left"
  },
  {
    "label": "Pan Right",
    "value": "kb-pan-right"
  },
  {
    "label": "Diagonal TL-BR",
    "value": "kb-diagonal-tl"
  },
  {
    "label": "Diagonal TR-BL",
    "value": "kb-diagonal-tr"
  }
];

var SITE_CONFIG_DEFAULTS = {
  "landing": {
    "logoMark": "OFL",
    "eyebrow": "Official Fantasy Commission",
    "title": "OFL",
    "subtitle": "Osborne Fantasy League",
    "tagline": "Where Legends Are Made & Legacies Are Settled",
    "backgroundFallbackColor": "#0a0a0a"
  },
  "slideshow": {
    "displayDuration": 4000,
    "fadeDuration": 2000,
    "overlay": "rgba(0,0,0,0.55)",
    "slides": [
      {
        "image": "assets/bg-01.jpg",
        "direction": "kb-pan-left"
      },
      {
        "image": "assets/bg-02.jpg",
        "direction": "kb-diagonal-tl"
      },
      {
        "image": "assets/bg-03.jpg",
        "direction": "kb-diagonal-tr"
      },
      {
        "image": "assets/bg-04.jpg",
        "direction": "kb-zoom-out"
      }
    ]
  },
  "menu": [
    {
      "label": "Home",
      "href": "index.html",
      "external": false
    },
    {
      "label": "the Playas",
      "href": "playas.html",
      "external": false
    },
    {
      "label": "OFC",
      "href": "league.html?league=ofc",
      "external": false
    },
    {
      "label": "BRC",
      "href": "league.html?league=brc",
      "external": false
    },
    {
      "label": "Standings",
      "href": "#",
      "external": false
    },
    {
      "label": "History",
      "href": "#",
      "external": false
    },
    {
      "label": "Commish Zone",
      "href": "index-admin.html",
      "external": false
    }
  ],
  "drawerFooter": "OFL · Est. 2005",
  "theme": {
    "accentColor": "#e8e8e8",
    "accentDim": "#ababab",
    "accentGlow": "rgba(232,232,232,0.08)",
    "hintColor": "#828282",
    "drawerBackground": "#0d0d0d",
    "drawerBorder": "rgba(232,232,232,0.08)",
    "fontDisplay": "'Oswald', sans-serif",
    "fontBody": "'Syne', sans-serif",
    "fontSizes": {
      "eyebrow": "8pt",
      "title": "72pt",
      "subtitle": "10pt",
      "tagline": "12pt",
      "navItem": "18pt",
      "navFooter": "7pt",
      "cardSport": "7pt",
      "cardName": "16pt",
      "cardCta": "8pt",
      "adminLabel": "9pt",
      "adminHint": "8pt",
      "sectionHeading": "9pt",
      "champTitle": "12pt",
      "champTeam": "42pt",
      "champOwner": "10pt",
      "champScore": "8pt"
    },
    "fontBold": {
      "eyebrow": false,
      "title": false,
      "subtitle": false,
      "tagline": false,
      "navItem": false,
      "navFooter": false,
      "cardSport": false,
      "cardName": false,
      "cardCta": false,
      "adminLabel": false,
      "adminHint": false,
      "sectionHeading": true,
      "champTitle": false,
      "champTeam": true,
      "champOwner": false,
      "champScore": false
    }
  },
  "footer": {
    "show": true,
    "text": "© 2025 OFL · All Rights Reserved"
  },
  "masterRoster": [
    {
      "id": "mbr_001",
      "name": "spider",
      "nickname": "The Commish",
      "active": true,
      "mugshot": "assets/mugs/spider.png",
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "spiders",
              "logo": "assets/logos/spiders.png"
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "theWeb",
              "logo": ""
            },
            {
              "name": "SilkySmooth"
            },
            {
              "name": "WebMaster"
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_002",
      "name": "Big Rob",
      "nickname": "BR",
      "active": true,
      "mugshot": "assets/mugs/br.png",
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "ATLiens",
              "logo": "assets/logos/ATLiens.png"
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "ATLiens",
              "logo": ""
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_003",
      "name": "Bubba",
      "nickname": "the Colonel",
      "active": true,
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "Flying Bubbas",
              "logo": "assets/logos/flyingbubbas.png"
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Dribbling Bubba's",
              "logo": ""
            }
          ]
        }
      ],
      "mugshot": "assets/mugs/bubba.png"
    },
    {
      "id": "mbr_004",
      "name": "Evan",
      "nickname": "EE",
      "active": true,
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "Boknowsbest",
              "logo": ""
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "InPearlWeTrust",
              "logo": ""
            },
            {
              "name": "BarkleyKnows"
            }
          ]
        }
      ],
      "mugshot": "assets/mugs/ee.png"
    },
    {
      "id": "mbr_005",
      "name": "William",
      "nickname": "Ozzy",
      "active": true,
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "Ozsome",
              "logo": ""
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Ozzy",
              "logo": ""
            },
            {
              "name": "LilZepInYourStep"
            }
          ]
        }
      ],
      "mugshot": "assets/mugs/ozzy.png"
    },
    {
      "id": "mbr_006",
      "name": "Amy",
      "nickname": "Ladybug",
      "active": true,
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "Molly Defenders",
              "logo": ""
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Bustin' Balls Bracket",
              "logo": ""
            },
            {
              "name": "Amy's Amazing Bracket"
            }
          ]
        }
      ],
      "mugshot": "assets/mugs/ladybug.png"
    },
    {
      "id": "mbr_007",
      "name": "Sonya",
      "nickname": "Browns",
      "active": true,
      "leagues": [
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Brownie Points",
              "logo": ""
            },
            {
              "name": "Dirty Dolly",
              "logo": ""
            },
            {
              "name": "PearlsJam"
            }
          ]
        }
      ],
      "mugshot": "assets/mugs/browns.png"
    },
    {
      "id": "mbr_mm161lj76qt7",
      "name": "Sherry Beth",
      "nickname": "Gangan",
      "mugshot": "assets/mugs/gangan.png",
      "active": true,
      "leagues": [
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Gangan Quilters"
            },
            {
              "name": "Quilting Babe"
            },
            {
              "name": "Ahsome GanGan"
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_mm1629iqfyaj",
      "name": "Ansley",
      "nickname": "Sissy",
      "mugshot": "assets/mugs/sissy.png",
      "active": true,
      "leagues": [
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Beaming Balls Bracket"
            },
            {
              "name": "ansley-oop"
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_mm1635nfdqvt",
      "name": "Kayla",
      "nickname": "K-Dawg",
      "mugshot": "assets/mugs/kdawg.png",
      "active": true,
      "leagues": [
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "pickocalypse"
            },
            {
              "name": "kdawgs good"
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_mm164375ur1b",
      "name": "Emery",
      "nickname": "Lil ESO",
      "mugshot": "assets/mugs/emery.png",
      "active": true,
      "leagues": [
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Lil ESO"
            },
            {
              "name": "ESO"
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_mm164qiz6e6j",
      "name": "Tristan",
      "nickname": "Bear",
      "mugshot": "assets/mugs/bear.png",
      "active": true,
      "leagues": [
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "TiKO"
            }
          ]
        }
      ]
    }
  ],
  "leagueData": [
    {
      "id": "lg_001",
      "name": "OFC",
      "fullName": "Osborne Football Club",
      "sport": "football",
      "season": "2024-25",
      "link": "league.html?league=ofc",
      "linkLabel": "Enter League",
      "accentColor": "",
      "logo": "assets/logos/ofc.png",
      "slideshow": {
        "displayDuration": 4000,
        "fadeDuration": 2000,
        "overlay": "rgba(0,0,0,0.55)",
        "slides": [
          {
            "image": "assets/bg-01.jpg",
            "direction": "kb-pan-left"
          },
          {
            "image": "assets/bg-02.jpg",
            "direction": "kb-diagonal-tr"
          }
        ]
      },
      "members": [
        "mbr_002",
        "mbr_003",
        "mbr_004",
        "mbr_005",
        "mbr_006",
        "mbr_001"
      ],
      "awards": {
        "champion": "Monster Lombardi",
        "regularSeasonChamp": "Bye Week Trophy",
        "highestTeamGameScore": "Stiff Arm Trophy",
        "highestIndividualScore": "Damn! Trophy",
        "seasonPointsLeader": "Bo Jackson Trophy",
        "mostPointsAgainst": "Hard Luck Trophy",
        "lastPlace": "Toilet Bowl Ring",
        "closestWin": "Nail Biter Award"
      },
      "cardTemplate": [
        {
          "key": "champion",
          "label": "Champion",
          "show": false
        },
        {
          "key": "championTeam",
          "label": "Champion Team",
          "show": true
        },
        {
          "key": "record",
          "label": "Record",
          "show": true
        },
        {
          "key": "championshipScore",
          "label": "Championship Score",
          "show": false
        },
        {
          "key": "seed",
          "label": "Playoff Seed",
          "show": false
        },
        {
          "key": "regularSeasonChamp",
          "label": "Reg. Season Champ",
          "show": false
        },
        {
          "key": "highestTeamGameScore",
          "label": "High Week Score",
          "show": false
        },
        {
          "key": "highestIndividualScore",
          "label": "High Player Score",
          "show": false
        },
        {
          "key": "seasonPointsLeader",
          "label": "Points Leader",
          "show": false
        },
        {
          "key": "teamsInLeague",
          "label": "Teams in League",
          "show": false
        }
      ],
      "seasons": [
        {
          "id": "ssn_001",
          "year": "2025",
          "championMemberId": "mbr_001",
          "championName": "spider",
          "championTeamName": "spiders",
          "runnerUpMemberId": "mbr_005",
          "runnerUpName": "William",
          "runnerUpTeamName": "Ozsome",
          "record": "9-8",
          "seed": "4",
          "championshipScore": "Ozsome 92.58 – spiders 131.22",
          "story": "A dominant wire-to-wire season. Owner One led the regular season and never looked back in the playoffs.",
          "image": "",
          "teamsInLeague": 6,
          "scoringSystem": "",
          "roster": [
            {
              "memberId": "mbr_001",
              "ownerName": "spider",
              "teamName": "spiders",
              "logo": ""
            },
            {
              "memberId": "mbr_002",
              "ownerName": "Big Rob",
              "teamName": "ATLiens",
              "logo": ""
            },
            {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "teamName": "Flying Bubbas",
              "logo": ""
            },
            {
              "memberId": "mbr_004",
              "ownerName": "Evan",
              "teamName": "Boknowsbest",
              "logo": ""
            },
            {
              "memberId": "mbr_005",
              "ownerName": "William",
              "teamName": "Ozsome",
              "logo": ""
            },
            {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "teamName": "Molly Defenders",
              "logo": ""
            }
          ],
          "stats": {
            "regularSeasonChamp": {
              "memberId": "mbr_004",
              "ownerName": "Evan",
              "team": "Boknowsbest",
              "record": "11-4",
              "teamName": "Boknowsbest"
            },
            "highestTeamGameScore": {
              "memberId": "mbr_001",
              "ownerName": "spider",
              "team": "spiders",
              "score": 139.14,
              "week": 7,
              "teamName": "spiders"
            },
            "highestIndividualScore": {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "team": "Molly Defenders",
              "playerName": "Derrick Henry",
              "points": 45.6,
              "teamName": "Molly Defenders"
            },
            "seasonPointsLeader": {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "team": "Flying Bubbas",
              "playerName": "Josh Allen",
              "total": 374.62,
              "teamName": "Flying Bubbas"
            },
            "mostPointsAgainst": {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "team": "Molly Defenders",
              "total": 1577.78,
              "teamName": "Molly Defenders"
            },
            "lastPlace": {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "team": "Flying Bubbas",
              "record": "6-10",
              "teamName": "Flying Bubbas"
            },
            "closestWin": {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "team": "Flying Bubbas",
              "opponent": "spiders",
              "margin": 0.36,
              "week": 8,
              "teamName": "Flying Bubbas"
            }
          },
          "standings": [
            {
              "rank": 1,
              "memberId": "mbr_001",
              "owner": "spider",
              "teamName": "spiders",
              "bracketName": "spiders",
              "record": "9-8",
              "pointsFor": "1445.48",
              "pointsAgainst": "1439.44"
            },
            {
              "rank": 2,
              "memberId": "mbr_005",
              "owner": "William",
              "teamName": "Ozsome",
              "bracketName": "Ozsome",
              "record": "9-8",
              "pointsFor": "1546.46",
              "pointsAgainst": "1488.42"
            },
            {
              "rank": 3,
              "memberId": "mbr_002",
              "owner": "Big Rob",
              "teamName": "ATLiens",
              "bracketName": "ATLiens",
              "record": "9-8",
              "pointsFor": "1540.56",
              "pointsAgainst": "1560.46"
            },
            {
              "rank": 4,
              "memberId": "mbr_004",
              "owner": "Evan",
              "teamName": "Boknowsbest",
              "bracketName": "Boknowsbest",
              "record": "11-6",
              "pointsFor": "1528.92",
              "pointsAgainst": "1464.40"
            },
            {
              "rank": 5,
              "memberId": "mbr_006",
              "owner": "Amy",
              "teamName": "Molly Defenders",
              "bracketName": "Molly Defenders",
              "record": "7-9",
              "pointsFor": "1597.52",
              "pointsAgainst": "1577.78"
            },
            {
              "rank": 6,
              "memberId": "mbr_003",
              "owner": "Bubba",
              "teamName": "Flying Bubbas",
              "bracketName": "Flying Bubbas",
              "record": "6-10",
              "pointsFor": "1438.76",
              "pointsAgainst": "1567.20"
            }
          ],
          "playoffs": {
            "semis": [
              {
                "homeMemberId": "mbr_005",
                "homeOwnerName": "William",
                "homeTeamName": "Ozsome",
                "homeScore": "123.3",
                "awayMemberId": "mbr_002",
                "awayOwnerName": "Big Rob",
                "awayTeamName": "ATLiens",
                "awayScore": "102.48"
              },
              {
                "homeMemberId": "mbr_004",
                "homeOwnerName": "Evan",
                "homeTeamName": "Boknowsbest",
                "homeScore": "94.36",
                "awayMemberId": "mbr_001",
                "awayOwnerName": "spider",
                "awayTeamName": "spiders",
                "awayScore": "108.6"
              }
            ],
            "finals": [
              {
                "homeMemberId": "mbr_005",
                "homeOwnerName": "William",
                "homeTeamName": "Ozsome",
                "homeScore": "92.58",
                "awayMemberId": "mbr_001",
                "awayOwnerName": "spider",
                "awayTeamName": "spiders",
                "awayScore": "131.22"
              }
            ],
            "consolation": [
              {
                "homeMemberId": "mbr_006",
                "homeOwnerName": "Amy",
                "homeTeamName": "Molly Defenders",
                "homeScore": "116.3",
                "awayMemberId": "mbr_003",
                "awayOwnerName": "Bubba",
                "awayTeamName": "Flying Bubbas",
                "awayScore": "84.98"
              },
              {
                "homeMemberId": "mbr_004",
                "homeOwnerName": "Evan",
                "homeTeamName": "Boknowsbest",
                "homeScore": "63.2",
                "awayMemberId": "mbr_002",
                "awayOwnerName": "Big Rob",
                "awayTeamName": "ATLiens",
                "awayScore": "81.98"
              }
            ],
            "wildcard": []
          },
          "customStats": [
            {
              "value": "30",
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "teamName": "Flying Bubbas",
              "winner": "Bubba — Flying Bubbas",
              "customAwardId": "ca_mm02a3dtvl6l"
            },
            {
              "customAwardId": "ca_mm1jks4c8i5l",
              "memberId": "",
              "ownerName": "",
              "teamName": "",
              "value": ""
            }
          ]
        }
      ],
      "heroEyebrow": "Osborne Football Club",
      "heroTitle": "OFC",
      "heroSubtitle": "Flinging mud, Family style",
      "pageLayout": {
        "showChampion": true,
        "showStandings": true,
        "showAwards": true,
        "showPastSeasons": true,
        "championImgSize": 400
      },
      "currentSeasonId": "ssn_001",
      "awardImages": {
        "champion": "assets/awards/brc-trophy-champion.jpg",
        "lastPlace": "assets/awards/brc-award-toilet ring.png"
      },
      "customAwards": [
        {
          "id": "ca_mm02a3dtvl6l",
          "label": "Realtor.com Award",
          "image": "",
          "description": "Most Transactions"
        },
        {
          "id": "ca_mm1jks4c8i5l",
          "label": "Cal Naughton Jr Ribbon",
          "image": "",
          "description": "Finishing Second"
        }
      ],
      "themeOverride": {
        "accentDim": "#d8d8d8",
        "hintColor": "#ecc098",
        "accentColor": "#ffffff",
        "drawerBorder": "#2b2b2b",
        "drawerBackground": ""
      }
    },
    {
      "id": "lg_002",
      "name": "BRC",
      "fullName": "Blue Ribbon Cup",
      "sport": "madness",
      "season": "2024-25",
      "link": "league.html?league=brc",
      "linkLabel": "Enter League",
      "accentColor": "",
      "logo": "assets/logos/brc.png",
      "slideshow": {
        "displayDuration": 4000,
        "fadeDuration": 2000,
        "overlay": "rgba(0,0,0,0.55)",
        "slides": [
          {
            "image": "assets/brc-bg-01.jpg",
            "direction": "kb-zoom-out"
          },
          {
            "image": "assets/brc-bg-02.jpg",
            "direction": "kb-diagonal-tr"
          }
        ]
      },
      "members": [
        "mbr_001",
        "mbr_002",
        "mbr_003",
        "mbr_004",
        "mbr_006"
      ],
      "awards": {
        "champion": "The Bracket King",
        "mostCorrectPicks": "The Oracle",
        "cinderellaPick": "The Cinderella Chaser",
        "earliestBust": "The First Out",
        "lastPlace": "The Participation Cup",
        "championshipCorrect": "The Crystal Ball",
        "bestSingleRound": "The Round Dominator",
        "finalFourCorrect": "The Prophet",
        "perfectBracketThrough": "The Unblemished"
      },
      "cardTemplate": [
        {
          "key": "winningBracket",
          "label": "Winning Bracket",
          "show": true
        },
        {
          "key": "correctPicks",
          "label": "Correct Picks",
          "show": true
        },
        {
          "key": "totalPoints",
          "label": "Total Points",
          "show": true
        },
        {
          "key": "actualWinner",
          "label": "Tournament Winner",
          "show": true
        },
        {
          "key": "mostCorrectPicks",
          "label": "Most Correct Picks",
          "show": true
        },
        {
          "key": "cinderellaPick",
          "label": "Cinderella Pick",
          "show": false
        },
        {
          "key": "perfectBracketThrough",
          "label": "Perfect Through",
          "show": false
        }
      ],
      "seasons": [
        {
          "id": "ssn_mm2cmgta5and",
          "year": "2025",
          "championMemberId": "mbr_mm161lj76qt7",
          "championName": "Sherry Beth",
          "championTeamName": "Gangan Quilters",
          "runnerUpMemberId": "mbr_001",
          "runnerUpName": "spider",
          "runnerUpTeamName": "theWeb",
          "record": "",
          "seed": "",
          "championshipScore": "",
          "story": "",
          "image": "",
          "teamsInLeague": 12,
          "scoringSystem": "",
          "roster": [
            {
              "memberId": "mbr_001",
              "ownerName": "spider",
              "teamName": "theWeb",
              "logo": ""
            },
            {
              "memberId": "mbr_002",
              "ownerName": "Big Rob",
              "teamName": "ATLiens",
              "logo": ""
            },
            {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "teamName": "Dribbling Bubba",
              "logo": ""
            },
            {
              "memberId": "mbr_004",
              "ownerName": "Evan",
              "teamName": "InPearlWeTrust",
              "logo": ""
            },
            {
              "memberId": "mbr_005",
              "ownerName": "William",
              "teamName": "Ozzy",
              "logo": ""
            },
            {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "teamName": "Bustin' Balls Bracket",
              "logo": ""
            },
            {
              "memberId": "mbr_007",
              "ownerName": "Sonya",
              "teamName": "Dirty Dolly",
              "logo": ""
            },
            {
              "memberId": "mbr_mm161lj76qt7",
              "ownerName": "Sherry Beth",
              "teamName": "Gangan Quilters",
              "logo": ""
            },
            {
              "memberId": "mbr_mm1629iqfyaj",
              "ownerName": "Ansley",
              "teamName": "Beaming Balls Bracket"
            },
            {
              "memberId": "mbr_mm1635nfdqvt",
              "ownerName": "Kayla",
              "teamName": "pickocalypse"
            },
            {
              "memberId": "mbr_mm164375ur1b",
              "ownerName": "Emery",
              "teamName": "Lil ESO"
            },
            {
              "memberId": "mbr_mm164qiz6e6j",
              "ownerName": "Tristan",
              "teamName": "TiKO"
            }
          ],
          "stats": {
            "winningBracket": {
              "memberId": "mbr_mm161lj76qt7",
              "ownerName": "Sherry Beth",
              "bracketName": "Gangan Quilters",
              "correctPicks": 0,
              "totalPoints": 125
            },
            "mostCorrectPicks": {
              "memberId": "",
              "ownerName": "",
              "bracketName": "",
              "count": 0
            },
            "perfectBracketThrough": [],
            "earliestBust": {
              "memberId": "",
              "ownerName": "",
              "round": ""
            },
            "cinderellaPick": {
              "memberId": "",
              "ownerName": "",
              "team": "",
              "round": ""
            },
            "bestSingleRound": [],
            "finalFourCorrect": [],
            "championshipCorrect": [],
            "lastPlace": {
              "memberId": "mbr_mm164qiz6e6j",
              "ownerName": "Tristan",
              "bracketName": "TiKO",
              "totalPoints": 0
            }
          },
          "standings": [
            {
              "rank": 1,
              "memberId": "mbr_mm161lj76qt7",
              "owner": "Sherry Beth",
              "bracketName": "Gangan Quilters",
              "correctPicks": "",
              "totalPoints": "125",
              "team": "Quilting Babe",
              "teamName": "Gangan Quilters"
            },
            {
              "rank": 2,
              "memberId": "mbr_001",
              "owner": "spider",
              "bracketName": "theWeb",
              "correctPicks": "",
              "totalPoints": "",
              "team": "SilkySmooth",
              "teamName": "theWeb"
            },
            {
              "rank": 3,
              "memberId": "mbr_002",
              "owner": "Big Rob",
              "bracketName": "ATLiens",
              "correctPicks": "",
              "totalPoints": "",
              "team": "ATLiens",
              "teamName": "ATLiens"
            },
            {
              "rank": 4,
              "memberId": "mbr_003",
              "owner": "Bubba",
              "bracketName": "Dribbling Bubba",
              "correctPicks": "",
              "totalPoints": "",
              "team": "Dribbling Bubba",
              "teamName": "Dribbling Bubba"
            },
            {
              "rank": 5,
              "memberId": "mbr_004",
              "owner": "Evan",
              "bracketName": "InPearlWeTrust",
              "correctPicks": "",
              "totalPoints": "",
              "team": "InPearlWeTrust",
              "teamName": "InPearlWeTrust"
            },
            {
              "rank": 6,
              "memberId": "mbr_005",
              "owner": "William",
              "bracketName": "Ozzy",
              "correctPicks": "",
              "totalPoints": "",
              "team": "Ozzy",
              "teamName": "Ozzy"
            },
            {
              "rank": 7,
              "memberId": "mbr_006",
              "owner": "Amy",
              "bracketName": "Bustin' Balls Bracket",
              "correctPicks": "",
              "totalPoints": "",
              "team": "Bustin' Balls Bracket",
              "teamName": "Bustin' Balls Bracket"
            },
            {
              "rank": 8,
              "memberId": "mbr_007",
              "owner": "Sonya",
              "bracketName": "Dirty Dolly",
              "correctPicks": "",
              "totalPoints": "",
              "team": "Dirty Dolly",
              "teamName": "Dirty Dolly"
            },
            {
              "rank": 9,
              "memberId": "mbr_mm1629iqfyaj",
              "owner": "Ansley",
              "bracketName": "Beaming Balls Bracket",
              "correctPicks": "",
              "totalPoints": "",
              "team": "Beaming Balls Bracket",
              "teamName": "Beaming Balls Bracket"
            },
            {
              "rank": 10,
              "memberId": "mbr_mm1635nfdqvt",
              "owner": "Kayla",
              "bracketName": "pickocalypse",
              "correctPicks": "",
              "totalPoints": "",
              "team": "pickocalypse",
              "teamName": "pickocalypse"
            },
            {
              "rank": 11,
              "memberId": "mbr_mm164375ur1b",
              "owner": "Emery",
              "bracketName": "Lil ESO",
              "correctPicks": "",
              "totalPoints": "",
              "team": "Lil ESO",
              "teamName": "Lil ESO"
            },
            {
              "rank": 12,
              "memberId": "mbr_mm164qiz6e6j",
              "owner": "Tristan",
              "bracketName": "TiKO",
              "correctPicks": "",
              "totalPoints": "",
              "team": "TiKO",
              "teamName": "TiKO"
            }
          ],
          "playoffs": {},
          "customStats": [
            {
              "customAwardId": "ca_mm02a3dtr563",
              "memberId": "",
              "ownerName": "",
              "teamName": "",
              "value": ""
            }
          ],
          "tournamentWinner": "Florida Gators"
        },
        {
          "id": "ssn_mm2alg8iuo42",
          "year": "2024",
          "championMemberId": "mbr_007",
          "championName": "Sonya",
          "championTeamName": "Brownie Points",
          "runnerUpMemberId": "mbr_mm161lj76qt7",
          "runnerUpName": "Sherry Beth",
          "runnerUpTeamName": "Quilting Babe",
          "record": "",
          "seed": "",
          "championshipScore": "",
          "story": "",
          "image": "",
          "teamsInLeague": 5,
          "scoringSystem": "",
          "roster": [
            {
              "memberId": "mbr_001",
              "ownerName": "spider",
              "teamName": "SilkySmooth",
              "logo": ""
            },
            {
              "memberId": "mbr_002",
              "ownerName": "Big Rob",
              "teamName": "ATLiens",
              "logo": ""
            },
            {
              "memberId": "mbr_007",
              "ownerName": "Sonya",
              "teamName": "Brownie Points",
              "logo": ""
            },
            {
              "memberId": "mbr_mm161lj76qt7",
              "ownerName": "Sherry Beth",
              "teamName": "Quilting Babe",
              "logo": ""
            },
            {
              "memberId": "mbr_mm1629iqfyaj",
              "ownerName": "Ansley",
              "teamName": "Beaming Balls Bracket",
              "logo": ""
            },
            {
              "memberId": "mbr_mm1635nfdqvt",
              "ownerName": "Kayla",
              "teamName": "pickocalypse",
              "logo": ""
            },
            {
              "memberId": "mbr_mm164375ur1b",
              "ownerName": "Emery",
              "teamName": "Lil ESO",
              "logo": ""
            },
            {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "teamName": "Dribbling Bubba",
              "logo": ""
            },
            {
              "memberId": "mbr_004",
              "ownerName": "Evan",
              "teamName": "InPearlWeTrust",
              "logo": ""
            },
            {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "teamName": "Bustin' Balls Bracket",
              "logo": ""
            },
            {
              "memberId": "mbr_005",
              "ownerName": "William",
              "teamName": "Ozzy",
              "logo": ""
            }
          ],
          "stats": {
            "winningBracket": {
              "memberId": "mbr_007",
              "ownerName": "Sonya",
              "bracketName": "Brownie Points",
              "correctPicks": 42,
              "totalPoints": 91
            },
            "mostCorrectPicks": {
              "memberId": "mbr_007",
              "ownerName": "Sonya",
              "bracketName": "Brownie Points",
              "count": 42
            },
            "perfectBracketThrough": [],
            "earliestBust": {
              "memberId": "",
              "ownerName": "",
              "round": ""
            },
            "cinderellaPick": {
              "memberId": "",
              "ownerName": "",
              "team": "",
              "round": ""
            },
            "bestSingleRound": [],
            "finalFourCorrect": [],
            "championshipCorrect": [],
            "lastPlace": {
              "memberId": "mbr_mm164375ur1b",
              "ownerName": "Emery",
              "bracketName": "Lil ESO",
              "totalPoints": 37
            }
          },
          "standings": [
            {
              "rank": 1,
              "memberId": "mbr_007",
              "owner": "Sonya",
              "teamName": "Brownie Points",
              "bracketName": "Brownie Points",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": "",
              "totalPoints": "91",
              "correctPicks": "42"
            },
            {
              "rank": 2,
              "memberId": "mbr_mm161lj76qt7",
              "owner": "Sherry Beth",
              "teamName": "Quilting Babe",
              "bracketName": "Quilting Babe",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": "",
              "totalPoints": "82",
              "correctPicks": ""
            },
            {
              "rank": 3,
              "memberId": "mbr_mm1635nfdqvt",
              "owner": "Kayla",
              "teamName": "pickocalypse",
              "bracketName": "pickocalypse",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": "",
              "totalPoints": "75",
              "correctPicks": ""
            },
            {
              "rank": 4,
              "memberId": "mbr_001",
              "owner": "spider",
              "bracketName": "SilkySmooth",
              "correctPicks": "",
              "totalPoints": "69",
              "team": "theWeb",
              "teamName": "SilkySmooth"
            },
            {
              "rank": 5,
              "memberId": "mbr_mm1629iqfyaj",
              "owner": "Ansley",
              "teamName": "Beaming Balls Bracket",
              "bracketName": "Beaming Balls Bracket",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": "",
              "totalPoints": "59",
              "correctPicks": ""
            },
            {
              "rank": 6,
              "memberId": "mbr_006",
              "owner": "Amy",
              "bracketName": "Bustin' Balls Bracket",
              "correctPicks": "",
              "totalPoints": "58",
              "team": "Bracket Six",
              "teamName": "Bustin' Balls Bracket"
            },
            {
              "rank": 7,
              "memberId": "mbr_002",
              "owner": "Big Rob",
              "bracketName": "ATLiens",
              "correctPicks": "",
              "totalPoints": "57",
              "team": "ATLiens",
              "teamName": "ATLiens"
            },
            {
              "rank": 8,
              "memberId": "mbr_003",
              "owner": "Bubba",
              "bracketName": "Dribbling Bubba",
              "correctPicks": "",
              "totalPoints": "56",
              "team": "Bracket Three",
              "teamName": "Dribbling Bubba"
            },
            {
              "rank": 9,
              "memberId": "mbr_005",
              "owner": "William",
              "teamName": "Ozzy",
              "bracketName": "Ozzy",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": "",
              "totalPoints": "49",
              "correctPicks": ""
            },
            {
              "rank": 10,
              "memberId": "mbr_004",
              "owner": "Evan",
              "bracketName": "InPearlWeTrust",
              "correctPicks": "",
              "totalPoints": "48",
              "team": "Bracket Four",
              "teamName": "InPearlWeTrust"
            },
            {
              "rank": 11,
              "memberId": "mbr_mm164375ur1b",
              "owner": "Emery",
              "teamName": "Lil ESO",
              "bracketName": "Lil ESO",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": "",
              "totalPoints": "37",
              "correctPicks": ""
            }
          ],
          "playoffs": {},
          "customStats": [
            {
              "customAwardId": "ca_mm02a3dtr563",
              "memberId": "",
              "ownerName": "",
              "teamName": "",
              "value": ""
            }
          ],
          "tournamentWinner": "UConn Huskies"
        },
        {
          "id": "ssn_mm2ontgybpzf",
          "year": "2023",
          "championMemberId": "mbr_003",
          "championName": "Bubba",
          "championTeamName": "Dribbling Bubba's",
          "runnerUpMemberId": "mbr_002",
          "runnerUpName": "Big Rob",
          "runnerUpTeamName": "ATLiens",
          "record": "",
          "seed": "",
          "championshipScore": "",
          "story": "This year's event featured loads of upsets where the 1, 2, & 3 seeds all failed to make the Final Four. Nobody had a Final Four team or championship team left after the Elite Eight games, so the Elite Eight turned a Championship run for the Dribbling Bubba's. Without a team left the Bubba's needed a losing trifecta to hold onto their slim lead and claim the coveted trophy. And that is exactly what happened when the Zags, KState, and Texas (and Creighton) all lost sending UConn, SDSU, FAU and Miami to Houston and Bubba's Dribbling off into the BRC sunset!",
          "image": "",
          "teamsInLeague": 12,
          "scoringSystem": "",
          "roster": [
            {
              "memberId": "mbr_001",
              "ownerName": "spider",
              "teamName": "WebMaster"
            },
            {
              "memberId": "mbr_002",
              "ownerName": "Big Rob",
              "teamName": "ATLiens",
              "logo": ""
            },
            {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "teamName": "Dribbling Bubba's",
              "logo": ""
            },
            {
              "memberId": "mbr_004",
              "ownerName": "Evan",
              "teamName": "BarkleyKnows"
            },
            {
              "memberId": "mbr_005",
              "ownerName": "William",
              "teamName": "LilZepInYourStep"
            },
            {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "teamName": "Amy's Amazing Bracket"
            },
            {
              "memberId": "mbr_007",
              "ownerName": "Sonya",
              "teamName": "PearlsJam"
            },
            {
              "memberId": "mbr_mm161lj76qt7",
              "ownerName": "Sherry Beth",
              "teamName": "Ahsome GanGan"
            },
            {
              "memberId": "mbr_mm1629iqfyaj",
              "ownerName": "Ansley",
              "teamName": "ansley-oop"
            },
            {
              "memberId": "mbr_mm1635nfdqvt",
              "ownerName": "Kayla",
              "teamName": "kdawgs good"
            },
            {
              "memberId": "mbr_mm164375ur1b",
              "ownerName": "Emery",
              "teamName": "ESO"
            },
            {
              "memberId": "mbr_mm164qiz6e6j",
              "ownerName": "Tristan",
              "teamName": "TiKO"
            }
          ],
          "stats": {
            "winningBracket": {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "bracketName": "Dribbling Bubba's",
              "correctPicks": 36,
              "totalPoints": 50
            },
            "mostCorrectPicks": {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "bracketName": "Dribbling Bubba's",
              "count": 36
            },
            "perfectBracketThrough": [],
            "earliestBust": {
              "memberId": "",
              "ownerName": "",
              "round": ""
            },
            "cinderellaPick": {
              "memberId": "",
              "ownerName": "",
              "team": "",
              "round": ""
            },
            "bestSingleRound": [],
            "finalFourCorrect": [],
            "championshipCorrect": [],
            "lastPlace": {
              "memberId": "mbr_mm164qiz6e6j",
              "ownerName": "Tristan",
              "bracketName": "TiKO",
              "totalPoints": 38
            }
          },
          "standings": [
            {
              "rank": 1,
              "memberId": "mbr_003",
              "owner": "Bubba",
              "bracketName": "Dribbling Bubba's",
              "totalPoints": "50",
              "correctPicks": "36",
              "team": "Dribbling Bubba's",
              "teamName": "Dribbling Bubba's"
            },
            {
              "rank": 2,
              "memberId": "mbr_002",
              "owner": "Big Rob",
              "bracketName": "ATLiens",
              "totalPoints": "47",
              "correctPicks": "",
              "team": "ATLiens",
              "teamName": "ATLiens"
            },
            {
              "rank": 3,
              "memberId": "mbr_004",
              "owner": "Evan",
              "bracketName": "BarkleyKnows",
              "totalPoints": "47",
              "correctPicks": "",
              "team": "BarkleyKnows",
              "teamName": "BarkleyKnows"
            },
            {
              "rank": 4,
              "memberId": "mbr_mm161lj76qt7",
              "owner": "Sherry Beth",
              "bracketName": "Ahsome GanGan",
              "totalPoints": "46",
              "correctPicks": "",
              "team": "Ahsome GanGan",
              "teamName": "Ahsome GanGan"
            },
            {
              "rank": 5,
              "memberId": "mbr_mm1635nfdqvt",
              "owner": "Kayla",
              "bracketName": "kdawgs good",
              "totalPoints": "46",
              "correctPicks": "",
              "team": "kdawgs good",
              "teamName": "kdawgs good"
            },
            {
              "rank": 6,
              "memberId": "mbr_005",
              "owner": "William",
              "bracketName": "LilZepInYourStep",
              "totalPoints": "44",
              "correctPicks": "",
              "team": "LilZepInYourStep",
              "teamName": "LilZepInYourStep"
            },
            {
              "rank": 7,
              "memberId": "mbr_006",
              "owner": "Amy",
              "bracketName": "Amy's Amazing Bracket",
              "totalPoints": "43",
              "correctPicks": "",
              "team": "Amy's Amazing Bracket",
              "teamName": "Amy's Amazing Bracket"
            },
            {
              "rank": 8,
              "memberId": "mbr_007",
              "owner": "Sonya",
              "bracketName": "PearlsJam",
              "totalPoints": "43",
              "correctPicks": "",
              "team": "PearlsJam",
              "teamName": "PearlsJam"
            },
            {
              "rank": 9,
              "memberId": "mbr_mm1629iqfyaj",
              "owner": "Ansley",
              "bracketName": "ansley-oop",
              "totalPoints": "43",
              "correctPicks": "",
              "team": "ansley-oop",
              "teamName": "ansley-oop"
            },
            {
              "rank": 10,
              "memberId": "mbr_mm164375ur1b",
              "owner": "Emery",
              "bracketName": "ESO",
              "totalPoints": "41",
              "correctPicks": "",
              "team": "ESO",
              "teamName": "ESO"
            },
            {
              "rank": 11,
              "memberId": "mbr_001",
              "owner": "spider",
              "bracketName": "WebMaster",
              "totalPoints": "39",
              "correctPicks": "",
              "team": "WebMaster",
              "teamName": "WebMaster"
            },
            {
              "rank": 12,
              "memberId": "mbr_mm164qiz6e6j",
              "owner": "Tristan",
              "bracketName": "TiKO",
              "totalPoints": "38",
              "correctPicks": "",
              "team": "TiKO",
              "teamName": "TiKO"
            }
          ],
          "playoffs": {},
          "customStats": [
            {
              "customAwardId": "ca_mm02a3dtr563",
              "memberId": "",
              "ownerName": "",
              "teamName": "",
              "value": ""
            }
          ],
          "tournamentWinner": "UConn Huskies"
        }
      ],
      "heroEyebrow": "Blue Ribbon Cup ",
      "heroTitle": "BRC",
      "heroSubtitle": "It's Blue Ribbon time!",
      "pageLayout": {
        "showChampion": true,
        "showStandings": true,
        "showAwards": true,
        "showPastSeasons": true
      },
      "currentSeasonId": "ssn_mm2cmgta5and",
      "awardImages": {},
      "customAwards": [
        {
          "id": "ca_mm02a3dtr563",
          "label": "Most Busted First Round Picks",
          "image": ""
        }
      ],
      "themeOverride": {
        "hintColor": "#98b8ec",
        "accentDim": "#d8d8d8",
        "accentColor": "#ffffff",
        "drawerBorder": "#2b2b2b"
      }
    }
  ],
  "leagues": [
    {
      "name": "OFC",
      "fullName": "Osborne Football Cup",
      "sport": "Football",
      "season": "2024-25",
      "link": "#",
      "linkLabel": "Enter League"
    },
    {
      "name": "BRC",
      "fullName": "Blue Ribbon Cup",
      "sport": "Basketball",
      "season": "2024-25",
      "link": "#",
      "linkLabel": "Enter League"
    }
  ]
};