/**
 * ============================================================
 *  ADMIN-CONFIG.JS — YOUR CONTENT & SETTINGS
 *  Generated by Admin Panel — 2/23/2026, 11:55:00 PM
 *
 *  This is YOUR file. Claude never modifies this.
 *  Load order: admin-config.js FIRST, then admin.js
 * ============================================================
 */

var ADMIN_PIN = "3432";

var KB_DIRECTIONS = [
  {
    "label": "Zoom In",
    "value": "kb-zoom-in"
  },
  {
    "label": "Zoom Out",
    "value": "kb-zoom-out"
  },
  {
    "label": "Pan Left",
    "value": "kb-pan-left"
  },
  {
    "label": "Pan Right",
    "value": "kb-pan-right"
  },
  {
    "label": "Diagonal TL-BR",
    "value": "kb-diagonal-tl"
  },
  {
    "label": "Diagonal TR-BL",
    "value": "kb-diagonal-tr"
  }
];

var SITE_CONFIG_DEFAULTS = {
  "landing": {
    "logoMark": "loading trash talk...",
    "eyebrow": "Official Fantasy Commission",
    "title": "OFL",
    "subtitle": "Osborne Fantasy League",
    "tagline": "Where Legends Are Made & Legacies Are Settled",
    "backgroundFallbackColor": "#0a0a0a"
  },
  "slideshow": {
    "displayDuration": 4000,
    "fadeDuration": 2000,
    "overlay": "rgba(0,0,0,0.55)",
    "slides": [
      {
        "image": "assets/bg-01.jpg",
        "direction": "kb-pan-left"
      },
      {
        "image": "assets/bg-02.jpg",
        "direction": "kb-diagonal-tl"
      },
      {
        "image": "assets/bg-03.jpg",
        "direction": "kb-diagonal-tr"
      },
      {
        "image": "assets/bg-04.jpg",
        "direction": "kb-zoom-out"
      }
    ]
  },
  "menu": [
    {
      "label": "Home",
      "href": "index.html",
      "external": false
    },
    {
      "label": "OFC — Football",
      "href": "league.html?league=ofc",
      "external": false
    },
    {
      "label": "BRC - Basketball",
      "href": "league.html?league=brc",
      "external": false
    },
    {
      "label": "Standings",
      "href": "#",
      "external": false
    },
    {
      "label": "History",
      "href": "#",
      "external": false
    },
    {
      "label": "Rules",
      "href": "#",
      "external": false
    },
    {
      "label": "Commissioner ",
      "href": "index-admin.html",
      "external": false
    }
  ],
  "drawerFooter": "OFL · Est. 2005",
  "theme": {
    "accentColor": "#e8e8e8",
    "accentDim": "#a6a6a6",
    "accentGlow": "rgba(232,232,232,0.08)",
    "hintColor": "#828282",
    "drawerBackground": "#0d0d0d",
    "drawerBorder": "rgba(232,232,232,0.08)",
    "fontDisplay": "'Oswald', sans-serif",
    "fontBody": "'Syne', sans-serif",
    "fontSizes": {
      "eyebrow": "8pt",
      "title": "72pt",
      "subtitle": "10pt",
      "tagline": "12pt",
      "navItem": "18pt",
      "navFooter": "7pt",
      "cardSport": "7pt",
      "cardName": "16pt",
      "cardCta": "8pt",
      "adminLabel": "9pt",
      "adminHint": "8pt",
      "sectionHeading": "9pt",
      "champTitle": "12pt",
      "champTeam": "42pt",
      "champOwner": "10pt",
      "champScore": "8pt"
    },
    "fontBold": {
      "eyebrow": false,
      "title": false,
      "subtitle": false,
      "tagline": false,
      "navItem": false,
      "navFooter": false,
      "cardSport": false,
      "cardName": false,
      "cardCta": false,
      "adminLabel": false,
      "adminHint": false,
      "sectionHeading": true,
      "champTitle": false,
      "champTeam": true,
      "champOwner": false,
      "champScore": false
    }
  },
  "footer": {
    "show": true,
    "text": "© 2025 OFL · All Rights Reserved"
  },
  "masterRoster": [
    {
      "id": "mbr_001",
      "name": "spider",
      "nickname": "The Commish",
      "active": true,
      "mugshot": "assets/mugs/spider.jpg",
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "spiders",
              "logo": "assets/logos/spiders.png"
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "theWeb",
              "logo": ""
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_002",
      "name": "Big Rob",
      "nickname": "BR",
      "active": true,
      "mugshot": "assets/mugs/br.png",
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "ATLiens",
              "logo": ""
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "ATLiens",
              "logo": ""
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_003",
      "name": "Bubba",
      "nickname": "the Colonel",
      "active": true,
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "Flying Bubbas",
              "logo": ""
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Bracket Three",
              "logo": ""
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_004",
      "name": "Evan",
      "nickname": "EE",
      "active": true,
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "Boknowsbest",
              "logo": ""
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Bracket Four",
              "logo": ""
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_005",
      "name": "William",
      "nickname": "Ozzy",
      "active": true,
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "Ozsome",
              "logo": ""
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Ozsome",
              "logo": ""
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_006",
      "name": "Amy",
      "nickname": "Ladybug",
      "active": true,
      "leagues": [
        {
          "leagueKey": "OFC",
          "leagueName": "",
          "teams": [
            {
              "name": "Molly Defenders",
              "logo": ""
            }
          ]
        },
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Bracket Six",
              "logo": ""
            }
          ]
        }
      ]
    },
    {
      "id": "mbr_007",
      "name": "Sonya",
      "nickname": "Browns",
      "active": true,
      "leagues": [
        {
          "leagueKey": "BRC",
          "leagueName": "",
          "teams": [
            {
              "name": "Brownie Points",
              "logo": ""
            },
            {
              "name": "Dirty Dolly",
              "logo": ""
            }
          ]
        }
      ]
    }
  ],
  "leagueData": [
    {
      "id": "lg_001",
      "name": "OFC",
      "fullName": "Osborne Football Club",
      "sport": "football",
      "season": "2024-25",
      "link": "league.html?league=ofc",
      "linkLabel": "Enter League",
      "accentColor": "",
      "logo": "assets/logos/ofc.png",
      "slideshow": {
        "displayDuration": 4000,
        "fadeDuration": 2000,
        "overlay": "rgba(0,0,0,0.55)",
        "slides": [
          {
            "image": "assets/ofc-bg-01.jpg",
            "direction": "kb-pan-left"
          },
          {
            "image": "assets/ofc-bg-02.jpg",
            "direction": "kb-zoom-in"
          }
        ]
      },
      "members": [
        "mbr_002",
        "mbr_003",
        "mbr_004",
        "mbr_005",
        "mbr_006",
        "mbr_001"
      ],
      "awards": {
        "champion": "The Lombardi",
        "regularSeasonChamp": "The Bye Week Trophy",
        "highestTeamGameScore": "The Stiff Arm",
        "highestIndividualScore": "The Heisman",
        "seasonPointsLeader": "The Cannon",
        "mostPointsAgainst": "The Hard Luck Trophy",
        "lastPlace": "The Toilet Bowl Crown",
        "closestWin": "The Nail Biter"
      },
      "cardTemplate": [
        {
          "key": "champion",
          "label": "Champion",
          "show": true
        },
        {
          "key": "championTeam",
          "label": "Champion Team",
          "show": true
        },
        {
          "key": "record",
          "label": "Record",
          "show": true
        },
        {
          "key": "championshipScore",
          "label": "Championship Score",
          "show": true
        },
        {
          "key": "seed",
          "label": "Playoff Seed",
          "show": false
        },
        {
          "key": "regularSeasonChamp",
          "label": "Reg. Season Champ",
          "show": false
        },
        {
          "key": "highestTeamGameScore",
          "label": "High Week Score",
          "show": false
        },
        {
          "key": "highestIndividualScore",
          "label": "High Player Score",
          "show": false
        },
        {
          "key": "seasonPointsLeader",
          "label": "Points Leader",
          "show": false
        },
        {
          "key": "teamsInLeague",
          "label": "Teams in League",
          "show": false
        }
      ],
      "seasons": [
        {
          "id": "ssn_001",
          "year": "2025",
          "championMemberId": "mbr_001",
          "championName": "spider",
          "championTeamName": "spiders",
          "runnerUpMemberId": "mbr_005",
          "runnerUpName": "William",
          "runnerUpTeamName": "Ozsome",
          "record": "9-8",
          "seed": "4",
          "championshipScore": "Ozsome 92.58 – spiders 131.22",
          "story": "A dominant wire-to-wire season. Owner One led the regular season and never looked back in the playoffs.",
          "image": "",
          "teamsInLeague": 6,
          "scoringSystem": "",
          "roster": [
            {
              "memberId": "mbr_001",
              "ownerName": "spider",
              "teamName": "spiders",
              "logo": "assets/logos/spiders.png"
            },
            {
              "memberId": "mbr_002",
              "ownerName": "Big Rob",
              "teamName": "ATLiens",
              "logo": ""
            },
            {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "teamName": "Flying Bubbas",
              "logo": ""
            },
            {
              "memberId": "mbr_004",
              "ownerName": "Evan",
              "teamName": "Boknowsbest",
              "logo": ""
            },
            {
              "memberId": "mbr_005",
              "ownerName": "William",
              "teamName": "Ozsome",
              "logo": ""
            },
            {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "teamName": "Molly Defenders",
              "logo": ""
            }
          ],
          "stats": {
            "regularSeasonChamp": {
              "memberId": "mbr_004",
              "ownerName": "Evan",
              "team": "Boknowsbest",
              "record": "11-4",
              "teamName": "Boknowsbest"
            },
            "highestTeamGameScore": {
              "memberId": "mbr_001",
              "ownerName": "spider",
              "team": "spiders",
              "score": 139.14,
              "week": 7,
              "teamName": "spiders"
            },
            "highestIndividualScore": {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "team": "Molly Defenders",
              "playerName": "Derrick Henry",
              "points": 45.6,
              "teamName": "Molly Defenders"
            },
            "seasonPointsLeader": {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "team": "Flying Bubbas",
              "playerName": "Josh Allen",
              "total": 374.62,
              "teamName": "Flying Bubbas"
            },
            "mostPointsAgainst": {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "team": "Molly Defenders",
              "total": 1577.78,
              "teamName": "Molly Defenders"
            },
            "lastPlace": {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "team": "Flying Bubbas",
              "record": "6-10",
              "teamName": "Flying Bubbas"
            },
            "closestWin": {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "team": "Flying Bubbas",
              "opponent": "spiders",
              "margin": 0.36,
              "week": 8,
              "teamName": "Flying Bubbas"
            }
          },
          "standings": [
            {
              "rank": 1,
              "memberId": "mbr_001",
              "owner": "spider",
              "teamName": "spiders",
              "bracketName": "spiders",
              "record": "9-8",
              "pointsFor": "1445.48",
              "pointsAgainst": "1439.44"
            },
            {
              "rank": 2,
              "memberId": "mbr_005",
              "owner": "William",
              "teamName": "Ozsome",
              "bracketName": "Ozsome",
              "record": "9-8",
              "pointsFor": "1546.46",
              "pointsAgainst": "1488.42"
            },
            {
              "rank": 3,
              "memberId": "mbr_002",
              "owner": "Big Rob",
              "teamName": "ATLiens",
              "bracketName": "ATLiens",
              "record": "9-8",
              "pointsFor": "1540.56",
              "pointsAgainst": "1560.46"
            },
            {
              "rank": 4,
              "memberId": "mbr_004",
              "owner": "Evan",
              "teamName": "Boknowsbest",
              "bracketName": "Boknowsbest",
              "record": "11-6",
              "pointsFor": "1528.92",
              "pointsAgainst": "1464.40"
            },
            {
              "rank": 5,
              "memberId": "mbr_006",
              "owner": "Amy",
              "teamName": "Molly Defenders",
              "bracketName": "Molly Defenders",
              "record": "7-9",
              "pointsFor": "1597.52",
              "pointsAgainst": "1577.78"
            },
            {
              "rank": 6,
              "memberId": "mbr_003",
              "owner": "Bubba",
              "teamName": "Flying Bubbas",
              "bracketName": "Flying Bubbas",
              "record": "6-10",
              "pointsFor": "1438.76",
              "pointsAgainst": "1567.20"
            }
          ],
          "playoffs": {
            "semis": [
              {
                "homeMemberId": "mbr_005",
                "homeOwnerName": "William",
                "homeTeamName": "Ozsome",
                "homeScore": "123.3",
                "awayMemberId": "mbr_002",
                "awayOwnerName": "Big Rob",
                "awayTeamName": "ATLiens",
                "awayScore": "102.48"
              },
              {
                "homeMemberId": "mbr_004",
                "homeOwnerName": "Evan",
                "homeTeamName": "Boknowsbest",
                "homeScore": "94.36",
                "awayMemberId": "mbr_001",
                "awayOwnerName": "spider",
                "awayTeamName": "spiders",
                "awayScore": "108.6"
              }
            ],
            "finals": [
              {
                "homeMemberId": "mbr_005",
                "homeOwnerName": "William",
                "homeTeamName": "Ozsome",
                "homeScore": "92.58",
                "awayMemberId": "mbr_001",
                "awayOwnerName": "spider",
                "awayTeamName": "spiders",
                "awayScore": "131.22"
              }
            ],
            "consolation": [
              {
                "homeMemberId": "mbr_006",
                "homeOwnerName": "Amy",
                "homeTeamName": "Molly Defenders",
                "homeScore": "116.3",
                "awayMemberId": "mbr_003",
                "awayOwnerName": "Bubba",
                "awayTeamName": "Flying Bubbas",
                "awayScore": "84.98"
              },
              {
                "homeMemberId": "mbr_004",
                "homeOwnerName": "Evan",
                "homeTeamName": "Boknowsbest",
                "homeScore": "63.2",
                "awayMemberId": "mbr_002",
                "awayOwnerName": "Big Rob",
                "awayTeamName": "ATLiens",
                "awayScore": "81.98"
              }
            ],
            "wildcard": []
          },
          "customStats": [
            {
              "value": "30",
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "teamName": "Flying Bubbas",
              "winner": "Bubba — Flying Bubbas",
              "customAwardId": "ca_mm02a3dtvl6l"
            }
          ]
        },
        {
          "id": "ssn_002",
          "year": "2023",
          "championMemberId": "mbr_002",
          "championName": "Owner Two",
          "championTeamName": "Team Bravo",
          "runnerUpMemberId": "mbr_001",
          "runnerUpName": "Owner One",
          "runnerUpTeamName": "Team Alpha",
          "record": "10-3",
          "seed": 2,
          "championshipScore": "138.9 – 122.4",
          "story": "The upset of the year. Owner Two came in as a 2-seed and knocked off the defending champion in the finals.",
          "image": "",
          "teamsInLeague": 6,
          "scoringSystem": "",
          "roster": [
            {
              "memberId": "mbr_001",
              "ownerName": "Owner One",
              "teamName": "Team Alpha",
              "logo": ""
            },
            {
              "memberId": "mbr_002",
              "ownerName": "Owner Two",
              "teamName": "Team Bravo",
              "logo": ""
            },
            {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "teamName": "Team Charlie",
              "logo": ""
            },
            {
              "memberId": "mbr_004",
              "ownerName": "Evan",
              "teamName": "Team Delta",
              "logo": ""
            },
            {
              "memberId": "mbr_005",
              "ownerName": "William",
              "teamName": "Team Echo",
              "logo": ""
            },
            {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "teamName": "Team Foxtrot",
              "logo": ""
            }
          ],
          "stats": {
            "regularSeasonChamp": {
              "memberId": "mbr_001",
              "ownerName": "Owner One",
              "team": "Team Alpha",
              "record": "11-2"
            },
            "highestTeamGameScore": {
              "memberId": "mbr_002",
              "ownerName": "Owner Two",
              "team": "Team Bravo",
              "score": 187.6,
              "week": 4
            },
            "highestIndividualScore": {
              "memberId": "mbr_004",
              "ownerName": "Owner Four",
              "team": "Team Delta",
              "playerName": "Another Star",
              "points": 48.6
            },
            "seasonPointsLeader": {
              "memberId": "mbr_001",
              "ownerName": "Owner One",
              "team": "Team Alpha",
              "playerName": "Top Player",
              "total": 1798.2
            },
            "mostPointsAgainst": {
              "memberId": "mbr_003",
              "ownerName": "Owner Three",
              "team": "Team Charlie",
              "total": 1612
            },
            "lastPlace": {
              "memberId": "mbr_007",
              "ownerName": "Owner Seven",
              "team": "Team Golf",
              "record": "2-11"
            },
            "closestWin": {
              "memberId": "mbr_002",
              "ownerName": "Owner Two",
              "team": "Team Bravo",
              "opponent": "Team Alpha",
              "margin": 1.2,
              "week": 9
            }
          },
          "standings": [
            {
              "rank": 1,
              "memberId": "mbr_001",
              "owner": "Owner One",
              "teamName": "Team Alpha",
              "bracketName": "Team Alpha",
              "record": "11-2",
              "pointsFor": 1798.2,
              "pointsAgainst": 1398.4
            },
            {
              "rank": 2,
              "memberId": "mbr_002",
              "owner": "Owner Two",
              "teamName": "Team Bravo",
              "bracketName": "Team Bravo",
              "record": "10-3",
              "pointsFor": 1642.8,
              "pointsAgainst": 1488.2
            },
            {
              "rank": 3,
              "memberId": "mbr_003",
              "owner": "Bubba",
              "teamName": "Team Charlie",
              "bracketName": "Team Charlie",
              "record": "7-6",
              "pointsFor": 1587.4,
              "pointsAgainst": 1612
            },
            {
              "rank": 4,
              "memberId": "mbr_004",
              "owner": "Evan",
              "teamName": "Team Delta",
              "bracketName": "Team Delta",
              "record": "7-6",
              "pointsFor": 1612.1,
              "pointsAgainst": 1544.3
            },
            {
              "rank": 5,
              "memberId": "mbr_005",
              "owner": "William",
              "teamName": "Team Echo",
              "bracketName": "Team Echo",
              "record": "4-9",
              "pointsFor": 1423.6,
              "pointsAgainst": 1598.1
            },
            {
              "rank": 6,
              "memberId": "mbr_006",
              "owner": "Amy",
              "teamName": "Team Foxtrot",
              "bracketName": "Team Foxtrot",
              "record": "4-9",
              "pointsFor": 1398,
              "pointsAgainst": 1622.2
            }
          ],
          "playoffs": {
            "semis": [
              {
                "homeMemberId": "mbr_001",
                "homeOwnerName": "Owner One",
                "homeTeamName": "Team Alpha",
                "homeScore": "148.2",
                "awayMemberId": "mbr_004",
                "awayOwnerName": "Evan",
                "awayTeamName": "Team Delta",
                "awayScore": "129.6"
              },
              {
                "homeMemberId": "mbr_002",
                "homeOwnerName": "Owner Two",
                "homeTeamName": "Team Bravo",
                "homeScore": "154.8",
                "awayMemberId": "mbr_003",
                "awayOwnerName": "Bubba",
                "awayTeamName": "Team Charlie",
                "awayScore": "142.1"
              }
            ],
            "finals": [
              {
                "homeMemberId": "mbr_002",
                "homeOwnerName": "Owner Two",
                "homeTeamName": "Team Bravo",
                "homeScore": "138.9",
                "awayMemberId": "mbr_001",
                "awayOwnerName": "Owner One",
                "awayTeamName": "Team Alpha",
                "awayScore": "122.4"
              }
            ],
            "consolation": [
              {
                "homeMemberId": "mbr_003",
                "homeOwnerName": "Bubba",
                "homeTeamName": "Team Charlie",
                "homeScore": "121.4",
                "awayMemberId": "mbr_004",
                "awayOwnerName": "Evan",
                "awayTeamName": "Team Delta",
                "awayScore": "108.8"
              }
            ],
            "wildcard": [
              {
                "homeMemberId": "",
                "homeOwnerName": "",
                "homeTeamName": "",
                "homeScore": "",
                "awayMemberId": "",
                "awayOwnerName": "",
                "awayTeamName": "",
                "awayScore": ""
              }
            ]
          },
          "customStats": [
            {
              "customAwardId": "ca_mm02a3dtvl6l",
              "memberId": "",
              "ownerName": "",
              "teamName": "",
              "value": ""
            }
          ]
        }
      ],
      "heroEyebrow": "Osborne Football Club",
      "heroTitle": "OFC",
      "heroSubtitle": "Flinging mud, Family style",
      "pageLayout": {
        "showChampion": true,
        "showStandings": true,
        "showAwards": true,
        "showPastSeasons": true,
        "championImgSize": 100
      },
      "currentSeasonId": "ssn_001",
      "awardImages": {
        "champion": "assets/awards/brc-trophy-champion.png"
      },
      "customAwards": [
        {
          "id": "ca_mm02a3dtvl6l",
          "label": "Most Transactions",
          "image": ""
        }
      ]
    },
    {
      "id": "lg_002",
      "name": "BRC",
      "fullName": "Blue Ribbon Cup",
      "sport": "madness",
      "season": "2024-25",
      "link": "league.html?league=brc",
      "linkLabel": "Enter League",
      "accentColor": "",
      "logo": "assets/logos/brc-logo.png",
      "slideshow": {
        "displayDuration": 4000,
        "fadeDuration": 2000,
        "overlay": "rgba(0,0,0,0.55)",
        "slides": [
          {
            "image": "assets/brc-bg-01.jpg",
            "direction": "kb-zoom-out"
          },
          {
            "image": "assets/brc-bg-02.jpg",
            "direction": "kb-diagonal-tr"
          }
        ]
      },
      "members": [
        "mbr_001",
        "mbr_002",
        "mbr_003",
        "mbr_004",
        "mbr_006"
      ],
      "awards": {
        "champion": "The Bracket King",
        "mostCorrectPicks": "The Oracle",
        "cinderellaPick": "The Cinderella Chaser",
        "earliestBust": "The First Out",
        "lastPlace": "The Participation Cup",
        "championshipCorrect": "The Crystal Ball",
        "bestSingleRound": "The Round Dominator",
        "finalFourCorrect": "The Prophet",
        "perfectBracketThrough": "The Unblemished"
      },
      "cardTemplate": [
        {
          "key": "winningBracket",
          "label": "Winning Bracket",
          "show": true
        },
        {
          "key": "correctPicks",
          "label": "Correct Picks",
          "show": true
        },
        {
          "key": "totalPoints",
          "label": "Total Points",
          "show": true
        },
        {
          "key": "actualWinner",
          "label": "Tournament Winner",
          "show": true
        },
        {
          "key": "mostCorrectPicks",
          "label": "Most Correct Picks",
          "show": true
        },
        {
          "key": "cinderellaPick",
          "label": "Cinderella Pick",
          "show": false
        },
        {
          "key": "perfectBracketThrough",
          "label": "Perfect Through",
          "show": false
        }
      ],
      "seasons": [
        {
          "id": "ssn_003",
          "year": "2025",
          "championMemberId": "mbr_003",
          "championName": "Owner Three",
          "championTeamName": "Bracket Three",
          "runnerUpMemberId": "mbr_001",
          "runnerUpName": "Owner One",
          "runnerUpTeamName": "Bracket One",
          "record": "",
          "seed": "",
          "championshipScore": "142 pts",
          "story": "Owner Three predicted the Cinderella run perfectly and rode it all the way to the Bracket King crown.",
          "image": "",
          "teamsInLeague": 5,
          "scoringSystem": "1-2-4-8-16-32",
          "roster": [
            {
              "memberId": "mbr_001",
              "ownerName": "spider",
              "teamName": "theWeb",
              "logo": ""
            },
            {
              "memberId": "mbr_003",
              "ownerName": "Bubba",
              "teamName": "Bracket Three",
              "logo": ""
            },
            {
              "memberId": "mbr_002",
              "ownerName": "Big Rob",
              "teamName": "ATLiens",
              "logo": ""
            },
            {
              "memberId": "mbr_004",
              "ownerName": "Evan",
              "teamName": "Bracket Four",
              "logo": ""
            },
            {
              "memberId": "mbr_006",
              "ownerName": "Amy",
              "teamName": "Bracket Six",
              "logo": ""
            },
            {
              "memberId": "mbr_007",
              "ownerName": "Sonya",
              "teamName": "Dirty Dolly",
              "logo": ""
            },
            {
              "memberId": "mbr_005",
              "ownerName": "William",
              "teamName": "Ozsome",
              "logo": ""
            }
          ],
          "stats": {
            "winningBracket": {
              "memberId": "mbr_003",
              "ownerName": "Owner Three",
              "bracketName": "Bracket Three",
              "correctPicks": 38,
              "totalPoints": 142
            },
            "actualTournamentWinner": "State University",
            "mostCorrectPicks": {
              "memberId": "mbr_003",
              "ownerName": "Owner Three",
              "bracketName": "Bracket Three",
              "count": 38
            },
            "perfectBracketThrough": [
              {
                "memberId": "mbr_001",
                "ownerName": "Owner One",
                "bracketName": "Bracket One",
                "round": "Sweet 16"
              }
            ],
            "earliestBust": {
              "memberId": "mbr_004",
              "ownerName": "Owner Four",
              "bracketName": "Bracket Four",
              "round": "Round of 64"
            },
            "cinderellaPick": {
              "memberId": "mbr_003",
              "ownerName": "Owner Three",
              "team": "Underdog U",
              "round": "Final Four"
            },
            "bestSingleRound": [
              {
                "memberId": "mbr_003",
                "ownerName": "Owner Three",
                "bracketName": "Bracket Three",
                "round": "Elite Eight",
                "points": 48
              }
            ],
            "finalFourCorrect": [
              {
                "memberId": "mbr_003",
                "ownerName": "Owner Three",
                "bracketName": "Bracket Three"
              }
            ],
            "championshipCorrect": [
              {
                "memberId": "mbr_003",
                "ownerName": "Owner Three",
                "bracketName": "Bracket Three"
              }
            ],
            "lastPlace": {
              "memberId": "mbr_004",
              "ownerName": "Owner Four",
              "bracketName": "Bracket Four",
              "totalPoints": 48
            }
          },
          "standings": [
            {
              "rank": 1,
              "memberId": "mbr_001",
              "owner": "spider",
              "teamName": "theWeb",
              "bracketName": "theWeb",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": ""
            },
            {
              "rank": 2,
              "memberId": "mbr_002",
              "owner": "Big Rob",
              "teamName": "ATLiens",
              "bracketName": "ATLiens",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": ""
            },
            {
              "rank": 3,
              "memberId": "mbr_003",
              "owner": "Bubba",
              "teamName": "Bracket Three",
              "bracketName": "Bracket Three",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": ""
            },
            {
              "rank": 4,
              "memberId": "mbr_004",
              "owner": "Evan",
              "teamName": "Bracket Four",
              "bracketName": "Bracket Four",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": ""
            },
            {
              "rank": 5,
              "memberId": "mbr_006",
              "owner": "Amy",
              "teamName": "Bracket Six",
              "bracketName": "Bracket Six",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": ""
            },
            {
              "rank": 6,
              "memberId": "mbr_007",
              "owner": "Sonya",
              "teamName": "Dirty Dolly",
              "bracketName": "Dirty Dolly",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": "",
              "totalPoints": "",
              "correctPicks": ""
            },
            {
              "rank": 7,
              "memberId": "mbr_005",
              "owner": "William",
              "teamName": "Ozsome",
              "bracketName": "Ozsome",
              "record": "",
              "pointsFor": "",
              "pointsAgainst": "",
              "totalPoints": "",
              "correctPicks": ""
            }
          ],
          "playoffs": {},
          "customStats": [
            {
              "value": "Owner Four — 8",
              "customAwardId": "ca_mm02a3dtr563"
            }
          ]
        }
      ],
      "heroEyebrow": "Blue Ribbon Cup ",
      "heroTitle": "BRC",
      "heroSubtitle": "It's Blue Ribbon time!",
      "pageLayout": {
        "showChampion": true,
        "showStandings": true,
        "showAwards": true,
        "showPastSeasons": true
      },
      "currentSeasonId": "ssn_003",
      "awardImages": {},
      "customAwards": [
        {
          "id": "ca_mm02a3dtr563",
          "label": "Most Busted First Round Picks",
          "image": ""
        }
      ]
    }
  ],
  "leagues": [
    {
      "name": "OFC",
      "fullName": "Osborne Football Cup",
      "sport": "Football",
      "season": "2024-25",
      "link": "#",
      "linkLabel": "Enter League"
    },
    {
      "name": "BRC",
      "fullName": "Blue Ribbon Cup",
      "sport": "Basketball",
      "season": "2024-25",
      "link": "#",
      "linkLabel": "Enter League"
    }
  ]
};